spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/simple_blog?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: admin123
    name: simple_blog

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        highlight_sql: true     # 컬러로 출력
        default_batch_fetch_size: 100

  security:
    user:
      name: user
      password: 1234
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_CLIENT_ID}"
            client-secret: "${GOOGLE_CLIENT_SECRET}"
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          kakao:
            client-id: "${KAKAO_REST_API_KEY}"
            client-secret: "${KAKAO_CLIENT_SECRET}"
            scope:
              - account_email
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post
          naver:
            client-id: "${NAVER_CLIENT_ID}"
            client-secret: "${NAVER_CLIENT_SECRET}"
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

jwt:
  secret: "${JWT_SECRET_CODE}"
  access-token-validity: 1800

cors:
  allowed-origins: http://localhost:8080

app:
  oauth2:
    authorized-redirect-uri: http://localhost:8080/user  # 소셜 로그인 후 리다이렉트될 URI

#logging:
#  level:
#    org.hibernate.SQL: debug          # SQL 쿼리 출력
#    org.hibernate.orm.jdbc.bind: trace    # 바인딩 파라미터 출력
#    org.hibernate.type.descriptor.sql: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true